# -*- coding: utf-8 -*-
"""DAU500Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pmQ6ZuDS6tBI1tRuRs_jFtNgSkDkUFXC

**Task 1 - PCA(Principal Component Analysis): a tool used to reduce the number of dimensions/features**
"""

# Commented out IPython magic to ensure Python compatibility.
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)

# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
np.random.seed(42)

# To plot pretty figures
# %matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "dim_reduction"
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID)
os.makedirs(IMAGES_PATH, exist_ok=True)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

"""**1- Load or create a dataset with more than 2 dimensions.**"""

from sklearn.datasets import make_classification
import pandas as pd

X, y = make_classification(n_samples=1000, n_features=5, n_classes=2, random_state=42)  #This line creates a dataset for classification.and each data has 1000 data points and each data points has 5 features and n_classes = 2 output labels

df = pd.DataFrame(X, columns=[f"Feature_{i+1}" for i in range(X.shape[1])]) #random_state ensures reproducibility. If someone else runs the same code with the same random_state, they get exactly the same result.
df['Target'] = y  #adds the output label to the data frame
df.head()

"""**2- Find the first 2 principal components with and without using sklearn.**
**(With sklearn)**
"""

from sklearn.decomposition import PCA

pca = PCA(n_components=2) #Out of your original 5 features, PCA will convert them into 2 new features (PC1 and PC2) and These 2 components capture the maximum variance in the data
X_pca_sklearn = pca.fit_transform(X) #dataset rotated into PCA space.

print("Principal components (sklearn):")
print(pca.components_)

"""(a) fit(X)

PCA learns patterns from dataset X
It calculates:
The mean of each feature,
The covariance matrix,
The eigenvalues (amount of variance),
The eigenvectors (principal components),

✔ (b) transform(X)
PCA projects/transforms your data onto the new 2D space,
So the output (X_pca_sklearn) has 2 columns:
PC1 (most variance),
PC2 (second most variance)
"""

import numpy as np #svd separates the data into vectors and values

X_centered = X - np.mean(X, axis=0) #PCA requires the dataset to be mean-centered.and np.mean(X, axis=0) calculates the mean of each feature column.

U, S, Vt = np.linalg.svd(X_centered) #X_centered is your dataset where each feature has mean = 0. and U → matrix of left singular vectors, S → singular values and Vt → matrix of right singular vectors (transposed)

principal_components = Vt[:2] #selects the first 2 rows
print("Principal components (manual):")
print(principal_components)

"""**3- Practice using PCA to preserve a certain percentage of variance.**"""

pca = PCA(0.95) #Choose the minimum number of components that together explain 95% of the total variance. and sklearn automatically computes how many components are needed
X_pca_95 = pca.fit_transform(X)

print(f"Number of components that explain 95% variance: {X_pca_95.shape[1]}") #.shape[1] gives the number of features after PCA (number of components chosen by PCA).

"""Output: You can safely reduce the dimensionality from 5 → 3 without losing much information.so that the variance is 95%

fit → PCA learns the patterns in your dataset (means, covariance, eigenvectors).
transform → Projects your original data onto the selected principal components.
X_pca_95 is now reduced-dimension data that preserves ~95% of the original variance.
"""

print(f"Explained variance ratio: {pca.explained_variance_ratio_}")

"""4- Train a classification or regression neural network by using:
   a) The Original dataset
   b) Principal components *
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)  #denotes the use of the original dataset

model = Sequential()
model.add(Dense(32, input_dim=X_train.shape[1], activation='relu')) #X_train.shape[1] → number of input features (columns) in the training data
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_test, y_test))

X_train_pca, X_test_pca = train_test_split(X_pca_sklearn, test_size=0.2, random_state=42) #the key line that uses PCA data instead of the original dataset. #X_pca_sklearn = your PCA-transformed dataset. Everything else in the network automatically uses this reduced feature set.

model_pca = Sequential()
model_pca.add(Dense(32, input_dim=X_train_pca.shape[1], activation='relu'))
model_pca.add(Dense(16, activation='relu'))
model_pca.add(Dense(1, activation='sigmoid'))

model_pca.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])
model_pca.fit(X_train_pca, y_train, epochs=20, batch_size=32, validation_data=(X_test_pca, y_test))

"""**5- Repeat part 4 using Kernel PCA (linear, sigmoid, RBF).**"""

from sklearn.decomposition import KernelPCA #non-linear extension of PCA, uses different kernels to capture complex structures in the data.

kernel_pca_linear = KernelPCA(kernel='linear', n_components=2)
kernel_pca_rbf = KernelPCA(kernel='rbf', gamma=15, n_components=2)
kernel_pca_sigmoid = KernelPCA(kernel='sigmoid', gamma=15, coef0=1, n_components=2)

X_pca_linear = kernel_pca_linear.fit_transform(X)
X_pca_rbf = kernel_pca_rbf.fit_transform(X)
X_pca_sigmoid = kernel_pca_sigmoid.fit_transform(X)

def train_model(X_train, y_train, X_test, y_test):
    model = Sequential()
    model.add(Dense(32, input_dim=X_train.shape[1], activation='relu'))
    model.add(Dense(16, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))

    model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])
    model.fit(X_train, y_train, epochs=20, batch_size=32, validation_data=(X_test, y_test))


X_train_kp, X_test_kp, y_train, y_test = train_test_split(X_pca_linear, y, test_size=0.2, random_state=42)
train_model(X_train_kp, y_train, X_test_kp, y_test)

X_train_kp, X_test_kp = train_test_split(X_pca_rbf, test_size=0.2, random_state=42)
train_model(X_train_kp, y_train, X_test_kp, y_test)

X_train_kp, X_test_kp = train_test_split(X_pca_sigmoid, test_size=0.2, random_state=42)
train_model(X_train_kp, y_train, X_test_kp, y_test)

"""kernel='linear' → behaves like normal linear PCA.,
kernel='rbf' → radial basis function (captures non-linear relationships), gamma=15 controls smoothness.,
kernel='sigmoid' → sigmoid kernel, gamma and coef0 are kernel parameters.,
n_components=2 → reduce data to 2 principal components for each kernel.

This function builds and trains a simple feedforward neural network:

2 hidden layers (32 & 16 neurons)

Output layer: 1 neuron, sigmoid activation for binary classification

input_dim=X_train.shape[1] → number of features (here 2 because of Kernel PCA)

Trains for 20 epochs, batch size 32, with validation on test set.
Totally trains one neural netowrk for 20 epochs so total 3 kernels

**6- Build a pipeline to tune the hyperparameters of Kernel PCA and also the neural network. Which hyperparameters can be tuned?**
"""

import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.decomposition import KernelPCA
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# Ensure scikeras is installed
!pip install scikeras

from scikeras.wrappers import KerasClassifier
from sklearn.preprocessing import StandardScaler

def create_nn_model(input_dim=2):
    model = Sequential()
    model.add(Dense(32, input_dim=input_dim, activation='relu'))
    model.add(Dense(16, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])
    return model


model = KerasClassifier(build_fn=create_nn_model, epochs=20, batch_size=32, verbose=0)


kpca = KernelPCA(n_components=2, eigen_solver="auto", remove_zero_eig=True)


pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('kpca', kpca),
    ('nn', model)
])

param_grid = {
    'kpca__kernel': ['linear', 'rbf'],
    'kpca__gamma': [0.01, 0.1, 0.5],
    'nn__batch_size': [16, 32],
    'nn__epochs': [10, 20],
    'nn__input_dim': [2]
}


X = np.random.rand(100, 3)
y = np.random.randint(0, 2, 100)

grid_search = GridSearchCV(pipeline, param_grid, cv=3, scoring='accuracy', verbose=2)
grid_search.fit(X, y)

print("Best parameters:", grid_search.best_params_)

pip install scikeras

import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.decomposition import KernelPCA
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from scikeras.wrappers import KerasClassifier
from sklearn.preprocessing import StandardScaler

# Upgrade scikeras to ensure compatibility with newer scikit-learn and Keras 3.x
!pip install scikeras --upgrade

def create_nn_model(input_dim=2):
    model = Sequential()
    model.add(Dense(32, input_dim=input_dim, activation='relu'))
    model.add(Dense(16, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])
    return model


model = KerasClassifier(build_fn=create_nn_model, epochs=20, batch_size=32, verbose=0)


kpca = KernelPCA(n_components=2, eigen_solver="auto", remove_zero_eig=True)


pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('kpca', kpca),
    ('nn', model)
])

param_grid = {
    'kpca__kernel': ['linear', 'rbf'],
    'kpca__gamma': [0.01, 0.1, 0.5],
    'nn__batch_size': [16, 32],
    'nn__epochs': [10, 20]
}

# Define X and y for the GridSearchCV
X = np.random.rand(100, 3)
y = np.random.randint(0, 2, 100)

grid_search = GridSearchCV(pipeline, param_grid, cv=3, scoring='accuracy', verbose=2)
grid_search.fit(X, y)

print("Best parameters:", grid_search.best_params_)

"""**Classification problem**
**1) Load IRIS and MNIST fashion datasets from Keras.**
"""

import tensorflow as tf
from tensorflow import keras
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import numpy as np

fashion_mnist = keras.datasets.fashion_mnist   #Loads 70,000 grayscale 28×28 images of clothing items.Returns 60,000 training samples + 10,000 test samples.
(X_train_fmnist, y_train_fmnist), (X_test_fmnist, y_test_fmnist) = fashion_mnist.load_data()

iris = datasets.load_iris()  #Iris has 150 samples, each with 4 features.y_iris contains labels {0, 1, 2} for the 3 flower types.
X_iris, y_iris = iris.data, iris.target #iris dataset download from scikit-learn

encoder = OneHotEncoder(sparse_output=False) #Converts integer labels like [0, 1, 2] into one-hot matrix: Necessary for training neural networks.and “Do not return a sparse matrix, return a normal dense array instead.”
y_iris = encoder.fit_transform(y_iris.reshape(-1, 1))

X_train_iris, X_test_iris, y_train_iris, y_test_iris = train_test_split(
    X_iris, y_iris, test_size=0.2, random_state=42
)

"""**2- Build and train a neural network for classifying the loaded labeled datasets.**"""

X_train_fmnist = X_train_fmnist / 255.0
X_test_fmnist = X_test_fmnist / 255.0


model_fmnist = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation='relu'), #Fully connected layer
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(10, activation='softmax')  #output layer
])

model_fmnist.compile(optimizer='adam',#adjusts the learning rate automatically during training.and Helps the model converge faster and more smoothly.
                     loss='sparse_categorical_crossentropy',#is used when we have multiple classes
                     metrics=['accuracy']) #Tells Keras to compute accuracy after each epoch.

history_fmnist = model_fmnist.fit(X_train_fmnist, y_train_fmnist,
                                  epochs=20, batch_size=32,
                                  validation_data=(X_test_fmnist, y_test_fmnist))

"""The model was trained for 20 epochs and showed consistent improvement. Training accuracy increased to 93.38%, while training loss steadily decreased to 0.1719, indicating effective learning. On the validation set, the model achieved an accuracy of approximately 88.65–88.91% with a validation loss around 0.355, showing good generalization to unseen data. Overall, the decreasing loss and increasing accuracy demonstrate that the model successfully learned to classify the data, with minimal overfitting."""

scaler = StandardScaler()
X_train_iris = scaler.fit_transform(X_train_iris)
X_test_iris = scaler.transform(X_test_iris)

model_iris = keras.Sequential([
    keras.layers.Dense(32, activation='relu', input_shape=(4,)),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(3, activation='softmax')
])

model_iris.compile(optimizer='adam',
                   loss='categorical_crossentropy',
                   metrics=['accuracy'])

history_iris = model_iris.fit(X_train_iris, y_train_iris,
                              epochs=50, batch_size=16,
                              validation_data=(X_test_iris, y_test_iris))

"""**3- Tune the hyperparameters (including hidden layer size and activation functions). What else can be tuned?**"""

pip install scikeras

pip install --upgrade scikit-learn scikeras tensorflow

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, GridSearchCV
from scikeras.wrappers import KerasClassifier
from tensorflow import keras

# 1️⃣ Load Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

X_train_iris, X_test_iris, y_train_iris, y_test_iris = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 2️⃣ Define model function
def create_model(activation='relu', optimizer='adam', neurons1=64, neurons2=32):
    model = keras.Sequential([
        keras.layers.Dense(neurons1, activation=activation, input_shape=(4,)),
        keras.layers.Dense(neurons2, activation=activation),
        keras.layers.Dense(3, activation='softmax')
    ])
    model.compile(
        optimizer=optimizer,
        loss='sparse_categorical_crossentropy',  # integer labels
        metrics=['accuracy']
    )
    return model

# 3️⃣ Wrap in SciKeras
model = KerasClassifier(model=create_model, verbose=0)

# 4️⃣ Define hyperparameter grid
# Note: all parameters of the model function must be prefixed with "model__"
param_grid = {
    'model__activation': ['relu', 'tanh'],
    'model__optimizer': ['adam', 'sgd'],
    'model__neurons1': [32, 64],
    'model__neurons2': [16, 32],
    'batch_size': [16, 32],
    'epochs': [30, 50]
}

# 5️⃣ Run GridSearchCV
grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=3)
grid.fit(X_train_iris, y_train_iris)

# 6️⃣ Results
print("Best Hyperparameters:", grid.best_params_)
print("Best Accuracy:", grid.best_score_)

"""Learning rate: Controls how quickly the model updates its weights.

Number of hidden layers: Adding or reducing layers can help the network learn more complex patterns.

Dropout rate: Helps prevent overfitting by randomly dropping neurons during training.

Regularization (L1/L2): Adds penalties to the loss function to reduce overfitting.

Weight initialization methods: Can affect how well and fast the model trains.

**4- Plot the loss and accuracy for training and testing datasets.**
"""

import matplotlib.pyplot as plt

def plot_history(history, title):
    plt.figure(figsize=(12, 4))

    # Accuracy plot
    plt.subplot(1, 2, 1)
    plt.plot(history.history.get('accuracy', []), label='Train Accuracy')
    plt.plot(history.history.get('val_accuracy', []), label='Validation Accuracy')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.title(f"{title} Accuracy")

    # Loss plot
    plt.subplot(1, 2, 2)
    plt.plot(history.history.get('loss', []), label='Train Loss')
    plt.plot(history.history.get('val_loss', []), label='Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.title(f"{title} Loss")

    plt.show()

plot_history(history_fmnist, "Fashion-MNIST")
plot_history(history_iris, "IRIS")

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint #MCP Save the model or weights during training

callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True), #Saves learned parameters (weights & biases). and restores weights of the best epoch
    ModelCheckpoint('best_model.h5', save_best_only=True)
]

model_fmnist.fit(X_train_fmnist, y_train_fmnist,
                 epochs=20, batch_size=32,
                 validation_data=(X_test_fmnist, y_test_fmnist),
                 callbacks=callbacks)

# Save weights
model_fmnist.save_weights("fashion_mnist.weights.h5")

# Load weights
model_fmnist.load_weights("fashion_mnist.weights.h5")

model_fmnist.save("fashion_mnist_model.h5")

loaded_model = keras.models.load_model("fashion_mnist_model.h5")

loss, acc = loaded_model.evaluate(X_test_fmnist, y_test_fmnist)
print(f"Loaded Model Accuracy: {acc:.4f}")

"""**Regression**
**1- Load California housing dataset and split it to training and testing datasets.**
"""

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

housing = fetch_california_housing()

X, y = housing.data, housing.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""**2- Build and train a neural network for price prediction. Tune the hyperparameters and discuss the results.**"""

import tensorflow as tf
from tensorflow import keras

model = keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1)
])

model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.01),
              loss='mse',
              metrics=['mae'])

history = model.fit(X_train, y_train, epochs=50, batch_size=32,
                    validation_data=(X_test, y_test), verbose=1)

"""**3- Plot the network history.**"""

import matplotlib.pyplot as plt

def plot_history(history, title):
    plt.figure(figsize=(12, 5))

    plt.subplot(1, 2, 1)
    plt.plot(history.history['loss'], label='Train Loss (MSE)')
    plt.plot(history.history['val_loss'], label='Validation Loss (MSE)')
    plt.xlabel('Epochs')
    plt.ylabel('Loss (MSE)')
    plt.legend()
    plt.title(f'{title} - Loss')

    plt.subplot(1, 2, 2)
    plt.plot(history.history['mae'], label='Train MAE')
    plt.plot(history.history['val_mae'], label='Validation MAE')
    plt.xlabel('Epochs')
    plt.ylabel('MAE')
    plt.legend()
    plt.title(f'{title} - MAE')

    plt.show()


plot_history(history, "California Housing Model")

"""**4- Change the learning rate. Train the network again and plot the network history. Discuss the results.**"""

model_lr = keras.Sequential([
    keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(1)
])

model_lr.compile(optimizer=keras.optimizers.Adam(learning_rate=0.001),
                 loss='mse',
                 metrics=['mae'])

history_lr = model_lr.fit(X_train, y_train, epochs=50, batch_size=32,
                          validation_data=(X_test, y_test), verbose=1)

plot_history(history_lr, "Lower Learning Rate Model")

"""**5- Save the weights of the layers and use callbacks during the training process.**"""

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True),
    ModelCheckpoint('best_california_model.h5', save_best_only=True)
]

model.fit(X_train, y_train, epochs=50, batch_size=32,
          validation_data=(X_test, y_test),
          callbacks=callbacks)

"""2 callbacks: EarlyStopping: stops training when the model stops improving.
ModelCheckpoint: saves the best version of the model during training.
A neural network learns by updating its weights (the internal values that determine predictions).

The EarlyStopping callback monitored the validation loss and automatically stopped training when the model stopped improving for 5 consecutive epochs. This prevents overfitting and saves training time. The ModelCheckpoint callback saved the best model (with the lowest validation loss) to a file, allowing the best-performing weights to be restored later.

**6- Practice saving and loading the trained model.**
"""

model.save("california_housing_model.h5")

pip install scikeras

model.save("california_housing_model.h5")

import tensorflow as tf
from tensorflow import keras

# Define custom objects to help Keras deserialize standard losses/metrics.
# This is necessary when loading models saved with older Keras versions or different formats
# because the string names for built-in losses/metrics might not be automatically recognized.
custom_objects = {
    'mse': tf.keras.losses.MeanSquaredError(),
    'mae': tf.keras.metrics.MeanAbsoluteError()
}

loaded_model = keras.models.load_model("california_housing_model.h5", custom_objects=custom_objects)

loss, mae = loaded_model.evaluate(X_test, y_test)
print(f"Loaded Model - Test MAE: {mae:.4f}")