# -*- coding: utf-8 -*-
"""DAU500thirdLab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wzNG6DSa0dit2L10DI9g8lpFodCQeG6Z

**Lab Assignment 3 - Learning rates, activation functions, and optimization algorithms**

**Multi-Layer Perceptron (MLP)** consists of fully connected dense layers that transform input data from one dimension to another. It is called multi-layer because it contains an input layer, one or more hidden layers and an output layer. The purpose of an MLP is to model complex relationships between inputs and outputs.
The goal of training an MLP is to minimize the loss function by adjusting the network's weights and biases. This is achieved through **backpropagation**

**1. Train a deep MLP on the MNIST dataset, you can load it using keras.datasets.mnist.load_data(). See if you can get over 98% precision. Try searching for the optimal learning rate (i.e., by growing the learning rate exponentially, plotting the error, and finding the point where the error shoots up), and plot learning curves using TensorBoard.**
"""

import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

(X_train, y_train), (X_test, y_test) = keras.datasets.mnist.load_data() #Loads the MNIST dataset (28×28 grayscale images of handwritten digits 0–9). load_data() returns two tuples: training data and test data.

X_train = X_train.astype("float32") / 255.0
X_test = X_test.astype("float32") / 255.0

X_train = X_train.reshape(-1, 28 * 28) #flatten each image
X_test = X_test.reshape(-1, 28 * 28)

y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

print(f"Training data shape: {X_train.shape}")
print(f"Testing data shape: {X_test.shape}")

"""keras.datasets.mnist.load_data() downloads the MNIST archive from the TensorFlow-hosted URL the first time you run it on a new machine. The training set contains 60,000 examples and the test set 10,000, and each example has been flattened to a vector of length 784 (28 × 28)."""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout #Dropout → regularization layer that randomly drops neurons to prevent overfitting

def build_model():
    model = Sequential([
        Dense(512, activation="relu", input_shape=(784,)),
        Dropout(0.2),
        Dense(256, activation="relu"),
        Dropout(0.2),
        Dense(128, activation="relu"),
        Dense(10, activation="softmax")
    ])
    return model

model = build_model()
model.compile(loss="categorical_crossentropy", optimizer=keras.optimizers.Adam(learning_rate=1e-3), metrics=["accuracy"])

model.summary()

"""Formula for dense layer: (input size x neurons) + biases = (784 x 512) + 512 = 401920
Dropout has no trainable parameters and same like for other dense layer

**Identify the largest learning rate that still decreases the loss**
"""

from tensorflow.keras.callbacks import LearningRateScheduler, History #change the learning rate during training

lr_schedule = keras.callbacks.LearningRateScheduler(lambda epoch: 1e-6 * 10**(epoch / 3)) #lambda epoch: ... → defines learning rate as a function of epoch.
history = History()

model = build_model()
model.compile(loss="categorical_crossentropy", optimizer=keras.optimizers.Adam(), metrics=["accuracy"])
history = model.fit(X_train, y_train, epochs=10, batch_size=128, callbacks=[lr_schedule], verbose=1)

lrs = 1e-6 * (10 ** (np.arange(10) / 3)) #lrs → array of learning rates used in each epoch (matches schedule)
losses = history.history["loss"]

plt.figure(figsize=(8, 6))
plt.semilogx(lrs, losses)
plt.xlabel("Learning Rate")
plt.ylabel("Loss")
plt.title("Finding Optimal Learning Rate")
plt.show()`

"""Training loss decreases if learning rate increases after that it becomes flatten if we still increase the learning rate, it becomes instability."""

from tensorflow.keras.callbacks import TensorBoard

optimal_lr = 1e-3 #based on found the suitable learning rate earlier

model = build_model()
model.compile(loss="categorical_crossentropy", optimizer=keras.optimizers.Adam(learning_rate=optimal_lr), metrics=["accuracy"])

tensorboard_cb = TensorBoard(log_dir="./logs", histogram_freq=1) #TensorBoard is a visualization tool for TensorFlow. (training logs will be stored, computes histogram of weights each epoch)

history = model.fit(X_train, y_train, epochs=20, batch_size=128, validation_data=(X_test, y_test), callbacks=[tensorboard_cb]) #sends data to TensorBoard for visualization

test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_acc:.4f}")

"""313/313 → The test dataset has 313 batches, and all of them were processed.

1s 4ms/step → On average, each batch took about 4 milliseconds, and the total evaluation took ~1 second.
Accuracy - These are the metrics reported per batch while evaluating the model

Your model is performing very well. It correctly predicts the labels for about 98.5% of the test data, and its predictions are very close to the true labels (low loss).
"""

import os
print(os.listdir("./logs")) #print the directory where training logs will be stored

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir=./logs

"""**2. Create a neural net for Fashion MNIST with 100 hidden layers, using the sigmoid, ReLU, ELU, and SELU activation functions, and discuss the vanishing/exploding gradients problem using each of the mentioned activation functions.**"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt

(x_train, y_train), (x_test, y_test) = keras.datasets.fashion_mnist.load_data()

x_train, x_test = x_train / 255.0, x_test / 255.0

x_train = x_train.reshape(-1, 784)
x_test = x_test.reshape(-1, 784)

print("Training set shape:", x_train.shape)
print("Test set shape:", x_test.shape)

"""**Function to create a model**"""

def create_model(activation_function):
    model = keras.Sequential()

    model.add(layers.Input(shape=(784,)))

    for _ in range(100):
        model.add(layers.Dense(64, activation=activation_function))

    model.add(layers.Dense(10, activation="softmax")) #outputs into probabilities that sum to 1

    model.compile(optimizer="adam",
                  loss="sparse_categorical_crossentropy", #labels were one hot encoded
                  metrics=["accuracy"])

    return model

activations = ["sigmoid", "relu", "elu", "selu"] #list of activation functions to test
history_dict = {}

for activation in activations:
    print(f"\nTraining model with {activation} activation...\n") #to create a model with that activation
    model = create_model(activation)

    history = model.fit(x_train, y_train, epochs=5, batch_size=256, validation_data=(x_test, y_test), verbose=1) #bacth size - no of samples per gradient update
    history_dict[activation] = history
    #This allows you to compare performance and training dynamics of different activation functions on the same network.

"""Vanishing gradient - Happens when gradients become very small as they are backpropagated through many layers.
Explodiing gradient - grow and large

**Sigmoid** - The loss does not decrease over epochs, indicating the network isn’t learning.Vanishing gradients: In very deep networks, gradients shrink as they are backpropagated through many layers. This causes weights in early layers to update very slowly, and the network stops learning effectively. Common with sigmoid/tanh activations.

Exploding gradients: Gradients grow exponentially as they are backpropagated. This can cause weights to become huge, making the network unstable and causing NaNs or divergence. Common with poor initialization or very deep networks.

**Relu :**This indicates that the network is not learning at all, despite ReLU being better than sigmoid in theory. No improvements after 5 epochs
Less of a problem with ReLU compared to sigmoid because gradient = 1 for positive inputs.

elu - Training accuracy is around 17–19% — better than random (10%) but still very low.
Validation accuracy fluctuates between 10%–20%, indicating unstable learning.
Loss fluctuates around ~2.0, also not steadily decreasing.
Vanishing gradient-	Some negative activations in deep layers have gradients < 1 (because ELU is smooth
Exploiding gradient - Multiplying through 100 layers can cause some weights to grow too fast → instability in loss/accuracy

selu SELU is very sensitive to input scaling and weight initialization.- Training and validation accuracy stuck around 10%, which is random guessing for 10 classes.
Loss values fluctuate around 2.31–2.32, showing no learning.
This is worse than ELU and ReLU in your previous experiments.
"""

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
for activation in activations:
    plt.plot(history_dict[activation].history['loss'], label=f"{activation}")

plt.title("Training Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()

plt.subplot(1, 2, 2)
for activation in activations:
    plt.plot(history_dict[activation].history['accuracy'], label=f"{activation}")

plt.title("Training Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()

plt.show()

"""1. Training Loss (Left Plot)
•	Sigmoid & ReLU: Both are very flat around 2.3, meaning the network barely improves during training.
•	ELU: Starts lower (1.92), spikes at epoch 1 (2.14), then decreases (1.99). Shows some learning but unstable in the beginning.
•	SELU: Starts high (2.35) and decreases slightly, but still very high. Poor learning.
2. Training Accuracy (Right Plot)

ELU: Starts around 0.19, dips to 0.16, then gradually increases to ~0.196. Shows learning, but overall accuracy is very low.

Sigmoid & ReLU: Around 0.098–0.10, almost no improvement.

SELU: Slightly higher than Sigmoid/ReLU at the start (~0.101) but decreases slightly.

**3. Practice training a deep neural network on the CIFAR10 image dataset. You can load it with keras.datasets.cifar10.load_data(). The dataset is composed of 60,000 32 × 32–pixel color images (50,000 for training, 10,000 for testing) with 10 classes, so you’ll need a softmax output layer with 10 neurons.**

The CIFAR-10 dataset stands for Canadian Institute For Advanced Research Dataset, where 10 stands for the count of representation classes, as discussed. The CIFAR-10 dataset contains 60,000 32x32 color images in 10 different classes, such as airplanes, cars, birds, cats, deer, dogs, frogs, horses, ships, and trucks.
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, ELU, Flatten, Input
from tensorflow.keras.optimizers import Nadam, SGD, RMSprop, Adam
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.initializers import HeNormal

(x_train, y_train), (x_test, y_test) = cifar10.load_data()

x_train, x_test = x_train / 255.0, x_test / 255.0

y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

pip install scikeras

from tensorflow.keras import optimizers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, ELU, Flatten, Input, Dropout
from tensorflow.keras.callbacks import EarlyStopping

def build_model_cifar10():
    model = Sequential([
        Input(shape=(32, 32, 3)), # Input for CIFAR10 images
        Flatten(), # Flatten the 32x32x3 image into a 3072-dimensional vector
        Dense(512),
        BatchNormalization(), #stabilizes training by normalizing inputs to the next layer.
        ELU(), #activation function that helps avoid vanishing gradients.
        Dropout(0.2),
        Dense(256),
        BatchNormalization(),
        ELU(),
        Dropout(0.2),
        Dense(128),
        BatchNormalization(),
        ELU(),
        Dropout(0.2),
        Dense(10, activation="softmax")
    ])
    return model

model = build_model_cifar10()

model.compile(optimizer=optimizers.Adam(),
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.summary()
early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

history = model.fit(x_train, y_train, epochs=50, batch_size=64, validation_data=(x_test, y_test), callbacks=[early_stopping])

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, ELU, Input, Flatten
from tensorflow.keras.initializers import HeNormal #Weight initializer suitable for layers with ReLU/ELU activations and specifically for ReLu/Elu
from tensorflow.keras.optimizers import Nadam #Nadam: Optimizer (like Adam but with Nesterov momentum).
from tensorflow.keras.callbacks import EarlyStopping

def build_model_with_batch_norm():
    model = Sequential()
    model.add(Input(shape=(32, 32, 3))) #32x32 RGB image
    model.add(Flatten())


    for _ in range(20):
        model.add(Dense(100, kernel_initializer=HeNormal()))
        model.add(BatchNormalization())
        model.add(ELU())

    model.add(Dense(10, activation='softmax'))

    model.compile(optimizer=Nadam(), loss='categorical_crossentropy', metrics=['accuracy'])

    return model

early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True) #model weights are restored to the best epoch not the last one

model_bn = build_model_with_batch_norm()
history_bn = model_bn.fit(x_train, y_train, epochs=50, batch_size=64, validation_data=(x_test, y_test), callbacks=[early_stopping])

def build_model():
    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(32, 32, 3)),  # <-- FIXED
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(10, activation='softmax')   # CIFAR10 has 10 classes
    ])
    return model

model_sgd = build_model()

model_sgd.compile(
    optimizer=SGD(),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history_sgd = model_sgd.fit(
    x_train, y_train,
    epochs=50,
    batch_size=64,
    validation_data=(x_test, y_test),
    callbacks=[early_stopping]
)

model_sgd = build_model()
model_sgd.compile(optimizer=SGD(), loss='categorical_crossentropy', metrics=['accuracy']) #Stochastic Gradient Descent to update the model’s weights during training.Can converge slowly if learning rate is not tuned.
history_sgd = model_sgd.fit(x_train, y_train, epochs=50, batch_size=64, validation_data=(x_test, y_test), callbacks=[early_stopping])

model_momentum = build_model() #Momentum is a technique to accelerate gradient descent and reduce oscillations during training.faster convergences, reduces oscillations and improve performance
model_momentum.compile(optimizer=SGD(momentum=0.9), loss='categorical_crossentropy', metrics=['accuracy'])
history_momentum = model_momentum.fit(x_train, y_train, epochs=50, batch_size=64, validation_data=(x_test, y_test), callbacks=[early_stopping])

from tensorflow.keras.optimizers import Adagrad #adapts the learning rate for each parameter individually

model_adagrad = build_model()

model_adagrad.compile(optimizer=Adagrad(), loss='categorical_crossentropy', metrics=['accuracy'])

history_adagrad = model_adagrad.fit(
    x_train, y_train,
    epochs=50, batch_size=64,
    validation_data=(x_test, y_test),
    callbacks=[early_stopping]
)

model_rmsprop = build_model() #adaptive optimizer that adjusts the learning rate for each parameter based on a moving average of recent squared gradients
model_rmsprop.compile(optimizer=RMSprop(), loss='categorical_crossentropy', metrics=['accuracy'])
history_rmsprop = model_rmsprop.fit(x_train, y_train, epochs=50, batch_size=64, validation_data=(x_test, y_test), callbacks=[early_stopping])

model_adam = build_model()
model_adam.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
history_adam = model_adam.fit(x_train, y_train, epochs=50, batch_size=64, validation_data=(x_test, y_test), callbacks=[early_stopping])

model_nadam = build_model()
model_nadam.compile(optimizer=Nadam(), loss='categorical_crossentropy', metrics=['accuracy'])
history_nadam = model_nadam.fit(x_train, y_train, epochs=50, batch_size=64, validation_data=(x_test, y_test), callbacks=[early_stopping])

model_nag = build_model()
opt_nag = SGD(learning_rate=0.01, momentum=0.9, nesterov=True)

model_nag.compile(optimizer=opt_nag, loss='categorical_crossentropy', metrics=['accuracy'])

history_nag = model_nag.fit(
    x_train, y_train,
    epochs=50,
    batch_size=64,
    validation_data=(x_test, y_test),
    callbacks=[early_stopping]
)

import matplotlib.pyplot as plt

def plot_history(histories, labels):
    plt.figure(figsize=(12, 8))
    for history, label in zip(histories, labels):
        plt.plot(history.history['val_accuracy'], label=label)
    plt.title('Model Validation Accuracy')
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.show()

histories = [history, history_bn, history_sgd, history_momentum, history_nag, history_adagrad, history_rmsprop, history_adam, history_nadam]
labels = ['No BatchNorm', 'BatchNorm', 'SGD', 'Momentum', 'NAG', 'AdaGrad', 'RMSprop', 'Adam', 'Nadam']
plot_history(histories, labels)

"""The learning curves show that Batch Normalization accelerates convergence and stabilizes training. Adaptive optimizers like Adam and Nadam reach higher validation accuracy faster, while plain SGD is slow and unstable. Momentum and NAG improve SGD performance, and RMSProp/Adagrad are intermediate.

Batch Normalization slightly increases computation per epoch but usually reduces total training time because the model converges in fewer epochs.
It stabilizes gradients, allowing higher learning rates and faster overall convergence.
"""